image: alpine/latest
packages:
  - go
sources:
  - https://github.com/emersion/go-pgpmail
tasks:
  - build: |
      cd go-pgpmail
      go build -v ./...
  - test: |
      cd go-pgpmail
      go test -v ./...
